server:
  port: 8080

spring:
  application:
    name: netflix-titles
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/titles
    username: bp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true